http_addr: ":8080"
shutdown_wait: "3s"

broker:
  mqtt_url: "tcp://mosquitto:1883"
  base_topic: "plant/readings"
  client_id: "edgelink-dev"

devices:
  - id: "press-1"
    type: "fake"
    poll_every: "1s"
    jitter: 0.05  # 5% jitter as float
    metric_names: ["temp_c", "pressure_bar"]

  - id: "press-2"
    type: "fake"
    poll_every: "750ms"
    jitter: 0.03  # 3% jitter as float
    metric_names: ["temp_c", "vibration_rms"]
