name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Get tag name
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Build for multiple platforms
      run: |
        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ steps.tag.outputs.tag }}" -o bin/edgelink-linux-amd64 ./cmd/edgelink
        
        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ steps.tag.outputs.tag }}" -o bin/edgelink-linux-arm64 ./cmd/edgelink
        
        # Windows amd64
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ steps.tag.outputs.tag }}" -o bin/edgelink-windows-amd64.exe ./cmd/edgelink
        
        # macOS amd64
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ steps.tag.outputs.tag }}" -o bin/edgelink-darwin-amd64 ./cmd/edgelink
        
        # macOS arm64
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ steps.tag.outputs.tag }}" -o bin/edgelink-darwin-arm64 ./cmd/edgelink
    
    - name: Create checksums
      run: |
        cd bin
        sha256sum * > checksums.txt
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/edgelink-go
        tags: |
          type=ref,event=tag
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/edgelink-*
          bin/checksums.txt
        body: |
          ## Changes
          
          See [CHANGELOG.md](CHANGELOG.md) for details.
          
          ## Installation
          
          ### Binary
          Download the appropriate binary for your platform from the assets below.
          
          ### Docker
          ```bash
          docker pull ${{ secrets.DOCKER_USERNAME }}/edgelink-go:${{ steps.tag.outputs.tag }}
          ```
          
          ### Go Install
          ```bash
          go install github.com/jstaud/edgelink-go/cmd/edgelink@${{ steps.tag.outputs.tag }}
          ```
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
